import { Metadata } from "next"
import Link from "next/link"
import { BioGeneratorTool } from "@/components/bio-generator-tool"
import { FaqAccordion } from "@/components/faq-accordion"
import { Sparkles, Zap, Target, Infinity as InfinityIcon, ShieldCheck } from "lucide-react"
import { WhyChooseUs } from "@/components/why-choose-us"
import { ExploreBioStyles } from "@/components/explore-bio-styles"
import { SeoContent } from "@/components/seo-content"
import { FadeIn, FadeInStagger, FadeInStaggerItem } from "@/components/animated-ui"

export const metadata: Metadata = {
  title: "Instagram Bio Generator – Create Unique Bios Instantly",
  description:
    "Discover the best instagram bio ideas and generate stunning, high-converting bios in seconds. Free AI-powered tool for aesthetic, stylish, and professional profiles.",
  alternates: {
    canonical: "/",
  },
}

export default function HomePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebSite",
            name: "InstaBioGen",
            url: "https://profilebiogenerator.site/",
            potentialAction: {
              "@type": "SearchAction",
              target: "https://profilebiogenerator.site/?category={search_term_string}",
              "query-input": "required name=search_term_string",
            },
          }),
        }}
      />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            mainEntity: [
              {
                "@type": "Question",
                name: "What is an Instagram bio maker and how does it work?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "An instagram bio maker is an AI-powered tool that generates unique, stylish, and optimized bios for your Instagram profile. You select a category, choose a tone, and the tool instantly creates multiple ready-to-use bio options tailored to your personality and goals.",
                },
              },
              {
                "@type": "Question",
                name: "Is this Instagram bio generator completely free?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "Yes, our tool is 100% free with no hidden charges, no subscriptions, and no sign-up required. You can generate unlimited bios without any restrictions.",
                },
              },
              {
                "@type": "Question",
                name: "Can I use these bios on other platforms?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "Absolutely. While optimized for Instagram, the bios generated by our instagram bio maker work perfectly on TikTok, Twitter (X), Facebook, YouTube, and any other social media platform.",
                },
              },
              {
                "@type": "Question",
                name: "How often should I update my Instagram bio?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "Social media experts recommend updating your bio every 4-6 weeks. Fresh bios signal activity to the algorithm and keep your profile aligned with current trends and your evolving brand.",
                },
              },
            ],
          }),
        }}
      />

      {/* Decorative Background Elements */}
      <div className="fixed inset-0 -z-10 bg-[url('/noise.png')] opacity-[0.02] mix-blend-overlay"></div>

      <main className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 bg-transparent text-foreground space-y-16 lg:space-y-24 overflow-hidden">

        {/* ============================================================
            1. HERO SECTION & TOOL (TOOL-FIRST DESIGN)
        ============================================================ */}
        <section id="generator-tool" className="relative mt-8 flex flex-col items-center justify-center space-y-12 scroll-mt-24">
          <div className="text-center space-y-10 z-10 w-full max-w-4xl mx-auto pb-4">
            
            {/* H1 — Universal Bio Generator */}
            <h1 className="pt-12 text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight whitespace-nowrap font-serif text-foreground leading-[1.05]">
              Free Bio Generator
            </h1>

            {/* INTRO PARAGRAPH */}
            <p className="mx-auto max-w-2xl text-lg sm:text-xl text-muted-foreground text-pretty font-sans leading-relaxed">
              Create the perfect bio for Instagram, TikTok, YouTube, LinkedIn, and more in seconds. Stand out, attract more followers, and make every single profile visitor hit that follow button.
            </p>
            
            {/* Social Proof removed as requested */}
          </div>

          <div className="w-full">
            <div className="relative rounded-3xl bg-background border border-border shadow-sm p-2 sm:p-4">
              <BioGeneratorTool />
            </div>
          </div>
        </section>

        {/* ============================================================
            4. HOW TO USE SECTION
        ============================================================ */}
        <section id="how-it-works" className="mx-auto max-w-5xl scroll-mt-24">
          <FadeIn className="text-center mb-16 space-y-4 flex flex-col items-center">
            <h2 className="section__h2 text-foreground">
              How to Use the Bio Generator
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Creating a standout bio takes just three simple steps. No sign-up, no downloads.
            </p>
          </FadeIn>
          
          <FadeInStagger className="flex flex-col gap-12 relative max-w-4xl mx-auto">
            <FadeInStaggerItem className="flex flex-col md:flex-row gap-6 md:w-3/4 items-start">
              <div className="text-7xl font-bold text-primary/20 select-none font-serif leading-none -mt-2">01</div>
              <div>
                <h3 className="text-2xl font-bold mb-2 text-foreground tracking-tight">Select Your Niche</h3>
                <p className="text-lg text-muted-foreground leading-relaxed">
                  Choose the category that best represents you or your brand (e.g., Creator, Business, Travel, Gaming).
                </p>
              </div>
            </FadeInStaggerItem>

            <FadeInStaggerItem className="flex flex-col md:flex-row gap-6 md:w-3/4 items-start">
              <div className="text-7xl font-bold text-primary/20 select-none font-serif leading-none -mt-2">02</div>
              <div>
                <h3 className="text-2xl font-bold mb-2 text-foreground tracking-tight">Pick a Tone</h3>
                <p className="text-lg text-muted-foreground leading-relaxed">
                  Decide on the vibe you want to project. Do you want to be Professional, Funny, Aesthetic, or Edgy?
                </p>
              </div>
            </FadeInStaggerItem>

            <FadeInStaggerItem className="flex flex-col md:flex-row gap-6 md:w-3/4 items-start relative">
              <div className="absolute -top-12 -right-12 w-32 h-32 bg-primary/10 rounded-full blur-3xl -z-10 hidden md:block"></div>
              <div className="text-7xl font-bold text-primary/20 select-none font-serif leading-none -mt-2">03</div>
              <div>
                <h3 className="text-2xl font-bold mb-2 text-foreground tracking-tight">Generate & Copy</h3>
                <p className="text-lg text-muted-foreground leading-relaxed">
                  Hit generate, browse multiple unique results, and copy the perfect bio directly to your clipboard.
                </p>
              </div>
            </FadeInStaggerItem>
          </FadeInStagger>
        </section>

        {/* ============================================================
            UNIQUE SECTION (HOME PAGE) - BEFORE & AFTER AI
        ============================================================ */}
        <section className="mx-auto max-w-5xl scroll-mt-24">
          <FadeIn className="text-center mb-16 space-y-4 flex flex-col items-center">
            <h2 className="section__h2 text-foreground">
              See the AI Difference
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Stop settling for boring profiles. See how our AI transforms a standard bio into a high-converting masterpiece.
            </p>
          </FadeIn>

          <FadeIn delay={0.2} className="grid md:grid-cols-2 gap-12 md:gap-16 max-w-4xl mx-auto items-center relative">
            {/* Divider for desktop */}
            <div className="hidden md:block absolute left-1/2 top-0 bottom-0 w-px bg-border/50 -translate-x-1/2"></div>
            
            {/* Before */}
            <div className="relative">
              <div className="inline-flex items-center gap-2 text-muted-foreground font-semibold mb-6 uppercase tracking-wider text-sm">
                <div className="w-2 h-2 rounded-full bg-red-500"></div>
                Before
              </div>
              <p className="text-muted-foreground text-xl leading-relaxed font-sans italic border-l-4 border-border pl-6 py-2">
                "Hi, I'm Sarah. I like coffee and traveling. Follow me for photos of my life. Business emails below."
              </p>
              <div className="mt-8 pt-6 border-t border-border/30 text-base text-muted-foreground">
                <span className="text-red-500/80 font-semibold uppercase text-xs tracking-widest block mb-1">Result</span>
                Low engagement, boring hook, hard to scan.
              </div>
            </div>

            {/* After */}
            <div className="relative group">
              <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 rounded-full blur-3xl -z-10 group-hover:bg-primary/10 transition-colors"></div>
              <div className="inline-flex items-center gap-2 text-primary font-bold mb-6 uppercase tracking-wider text-sm">
                <div className="w-2 h-2 rounded-full bg-primary animate-pulse shadow-[0_0_8px_rgba(37,99,235,0.8)]"></div>
                After AI
              </div>
              <p className="text-foreground text-xl leading-relaxed font-sans font-medium border-l-4 border-primary pl-6 py-2">
                ☕ Fueling adventures with iced coffee.<br/>
                ✈️ 20+ countries and counting.<br/>
                👇 Discover my travel presets!<br/>
                <span className="text-primary hover:underline cursor-pointer">linktr.ee/sarahstravels</span>
              </p>
              <div className="mt-8 pt-6 border-t border-border/30 text-base text-muted-foreground">
                <span className="text-primary font-semibold uppercase text-xs tracking-widest block mb-1">Result</span>
                Highly scannable, engaging emojis, strong CTA.
              </div>
            </div>
          </FadeIn>
        </section>

        {/* ============================================================
            5. EXPLORE STYLES
        ============================================================ */}
        <ExploreBioStyles />

        {/* ============================================================
            8. WHY CHOOSE US
        ============================================================ */}
        <WhyChooseUs />

        {/* ============================================================
            ARTICLES / SEO TEXT BLOCKS (Restyled into clean readable typography)
        ============================================================ */}
        <SeoContent />

        {/* ============================================================
            9. FAQ SECTION
        ============================================================ */}
        <FaqAccordion />

      </main>
    </>
  )
}
